Research Paper:

https://www.theringer.com/2017/6/14/16044264/2017-mlb-home-run-spike-juiced-ball-testing-reveal-155cd21108bc

Analyze and question the data that the scientists use

The question at hand here is rather simple: are juiced baseballs the reason for the dramatic increase in home run totals in the 2017 MLB season? This is a question that was rather pressing in the baseball world. As viewership began to decline due to many finding the game boring, many suspected that Major League Baseball altered the seams of their baseballs to increase the number of home runs. In their eyes, home runs equal excitement, and viewership wise, they’re not wrong. Originally, the only piece of data Lindbergh provides is the increased home run total. Alone, that is not enough to prove that the balls are different than previous years. The cause of the increase in home runs could be due to analytics or pure randomness. However, Lindbergh proceeds to analyze the seam heights of the baseballs, which is a much better piece of data to use. The lower the seams are on the baseball, the farther it will travel, as air resistance will play a much smaller role in slowing the ball down. Furthermore, while it is not based on data, Lindbergh does provide the counter argument to his claim that the balls are juiced. He brings in the voice of Alan Nathan, an expert on the physics of the game, who has no reason to believe that the balls are juiced. Overall, I believe that the data that Lindbergh uses is both accurate and helpful for determining whether or not the balls were juiced in the 2017 MLB season.

Analyze their results. Do you trust their findings? Why or why not?

I do trust Lindbergh’s findings for a couple reasons. First of all, the question of juiced balls by no means came out of nowhere. Everyone in the baseball community suspected the possibility of it at least. I was originally skeptical, because I thought Lindbergh was using the home run totals to prove causation. However, he won me over by studying the seam height differences, and referencing the NCAA study that showed the effect of lowering the seams from 0.48 inches to 0.31 inches. The research on COR also showed the differences in the baseballs used in MLB. It also analyzes the history of baseball to prove that these otherworldly home run rates are just that: otherworldly. I wish Lindbergh would dive more into the analytical revolution that baseball has seen, because that is also a possible catalyst for the increase in home runs. Several batters are instructed to adopt a more uppercut swing, which may increase strikeout totals, but also help the long ball. However, I trust Lindbergh’s findings overall, because he backs it up with valuable data that helps prove his argument. 

How might “publish or perish” have affected this study?

In this instance, I do not think publish or perish played too large of a role. Lindbergh’s process seems to be carefully crafted and not particularly rushed. With that said, I am sure that Lindbergh knew that he would not be the only baseball researcher to write a paper about this. There are two strong ways to generate clicks: write the best paper or write the first paper. It is clear that Lindbergh attempted to do both. I think it would have been interesting if he conducted studies himself about the distances of baseballs based on their seam height. For instance, if he went to a baseball field with a fly-ball machine and a bunch of different baseballs. He could place each different ball in the machine and analyze how far it travels. However, I think Lindbergh’s process was both thorough and efficient.
